config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get "dashboard"    => "users#show",         as: :dashboard
  get "sign-up"      => "users#new",          as: :sign_up
  post "save-email"  => "users#save_email",   as: :save_email
  get "new-password" => "users#new_password", as: :new_password
  post "users"       => "users#create",       as: :create_user

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email,
    presence: true,
    uniqueness: true,
    format: { with: /(\A([a-z]*\s*)*\<*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\>*\Z)/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end

  def new
    @user = User.new
  end

  def save_email
    session[:email] = params[:user][:email]
    redirect_to new_password_path
  end

  def new_password
    @user = User.new(email: session[:email])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to dashboard_path, notice: "User created successfully."
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Silent Sail" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/users/new.html.erb
<%= form_with(model: @user, url: save_email_path, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.email_field :email, required: true, class: "form-control" %>
  </div>
  <%= form.submit "Next", class: "btn btn-primary" %>
<% end %>

app/views/users/new_password.html.erb
<h1>New Password</h1>